### ISSUE TITLE
Buffer error

### ISSUE THREAD

**Issue by kazukikun24** [OguzhanUmutlu/DiscordToMCPE_TR#2]
this buffer is old.. you should update it please :)

**Comment by kazukikun24** [comment]
Help :)

**Comment by kazukikun24** [comment]
`
const app = express();

app.get("/", (req,res) => {
    if((new Buffer(req.query.key, "base64")).toString("utf-8") == key && req.query.message) {
        let message = (new Buffer(req.query.message, "base64")).toString("utf-8");
        onWebhookMessage(message);
    }
})

app.listen(3000);

module.exports = {getClient:function(){return client;}};
`
Dmn

**Comment by kazukikun24** [comment]
![Uploading Screenshot_2021-07-31-03-46-20-297_com.sonelli.juicessh.jpg…]()
Look

**Comment by kazukikun24** [comment]
[https://github.com/OguzhanUmutlu/DiscordToMCPE_TR/blob/01e4973c442085ecd677041a789141436939036a/bot/index.js#L182](url)

**Comment by kazukikun24** [comment]
![Screenshot_2021-07-31-03-46-20-297_com sonelli juicessh](https://user-images.githubusercontent.com/79141593/127710111-d2e00aea-9f0a-406c-a20b-ba32f8a28570.jpg)

**Comment by OguzhanUmutlu** [comment]
wrong rcon password
